Yevdokimov Danil | Attention, wanted in Arcane!
st084331/myStreamlitApp pull request #3
Opened 2022-12-08 15:34 UTC by st084331

Did it!

2022-12-09 15:18 UTC, SpirinEgor requested changes
For now, your code is a mix of global statements and functions. Let's organize it a little bit and make explicit the main method. This main method will init all states and define app structure. You can call it under `if __name__ == "__main__"` statement.

2022-12-09 15:18 UTC, SpirinEgor commented on .idea/.gitignore
> -# Default ignored files
Delete these files in the main branch and fetch changes here. So they don't appear in PR.

2022-12-09 15:18 UTC, SpirinEgor commented on README.md
> +Не забудьте сделать pip install -r requirements.txt
But you don't have a `requirements.txt` file in PR and repo at all.

2022-12-09 15:18 UTC, SpirinEgor commented on main.py
> +model_id = "nitrosocke/Arcane-Diffusion"
Conventionally, it is better to use UPPER_CASE for constants.
```python
MODEL_ID = "nitrosocke/Arcane-Diffusion"
```

2022-12-09 15:18 UTC, SpirinEgor commented on main.py
> +    # Лаконично и понятно, думаю менять не стоит
If you have something to say for me or anyone else, it should be done in discussion or in chat. 😅
Comments in the code are for clarification, not for discussion.

2022-12-09 15:32 UTC, st084331 commented on main.py
> +    # Лаконично и понятно, думаю менять не стоит
Okay, I'll learn.

2022-12-12 17:08 UTC, st084331 commented on .idea/.gitignore
> -# Default ignored files
Corrected

2022-12-14 12:33 UTC, SpirinEgor reviewed
Get rid of global pipe and then all will be okay!

2022-12-14 12:33 UTC, SpirinEgor commented on main.py
> +PIPE = init_pipe()
Why do you make it global if you cached it? You can call the function every time you need your pipeline.

2022-12-14 12:33 UTC, SpirinEgor commented on main.py
> +    return PIPE(prompt="arcane style, " + text, num_inference_steps=num_inference_steps,
You need a global variable only to use it in this function. That is strange 🤷‍♂️

2022-12-14 13:10 UTC, st084331 commented on main.py
> +PIPE = init_pipe()
You are right, I have corrected the error.

2022-12-16 11:31 UTC, merged